export const keyboardButtonsCode = [
    {code: 'Backquote', en: '`', ru: 'ё', printable: true},
    {code: 'Digit1', en: '1', ru: '1', isShiftEn: '!', isShiftRu: '!', printable: true},
    {code: 'Digit2', en: '2', ru: '2', isShiftEn: '@', isShiftRu: '"', printable: true},
    {code: 'Digit3', en: '3', ru: '3', isShiftEn: '#', isShiftRu: '№', printable: true},
    {code: 'Digit4', en: '4', ru: '4', isShiftEn: '$', isShiftRu: ';', printable: true},
    {code: 'Digit5', en: '5', ru: '5', isShiftEn: '%', isShiftRu: '%', printable: true},
    {code: 'Digit6', en: '6', ru: '6', isShiftEn: '^', isShiftRu: ':', printable: true},
    {code: 'Digit7', en: '7', ru: '7', isShiftEn: '&', isShiftRu: '?', printable: true},
    {code: 'Digit8', en: '8', ru: '8', isShiftEn: '*', isShiftRu: '*', printable: true},
    {code: 'Digit9', en: '9', ru: '9', isShiftEn: '(', isShiftRu: '(', printable: true},
    {code: 'Digit0', en: '0', ru: '0', isShiftEn: ')', isShiftRu: ')', printable: true},
    {code: 'Minus', en: '-', ru: '-', isShiftEn: '_', isShiftRu: '_', printable: true},
    {code: 'Equal', en: '=', ru: '=', isShiftEn: '+', isShiftRu: '+', printable: true},
    {code: 'Backspace', en: 'Backspace', ru: 'Backspace', printable: false},
    {code: 'Tab', en: 'Tab', ru: 'Tab', nonPrintableValues: '     ', printable: false},
    {code: 'KeyQ', en: 'q', ru: 'й', printable: true},
    {code: 'KeyW', en: 'w', ru: 'ц', printable: true},
    {code: 'KeyE', en: 'e', ru: 'у', printable: true},
    {code: 'KeyR', en: 'r', ru: 'к', printable: true},
    {code: 'KeyT', en: 't', ru: 'е', printable: true},
    {code: 'KeyY', en: 'y', ru: 'н', printable: true},
    {code: 'KeyU', en: 'u', ru: 'г', printable: true},
    {code: 'KeyI', en: 'i', ru: 'ш', printable: true},
    {code: 'KeyO', en: 'o', ru: 'щ', printable: true},
    {code: 'KeyP', en: 'p', ru: 'з', printable: true},
    {code: 'BracketLeft', en: '[', ru: 'х', isShiftEn: '{', printable: true},
    {code: 'BracketRight', en: ']', ru: 'ъ', isShiftEn: '}', printable: true},
    {code: 'Backslash', en: '\\', ru: '\\', isShiftEn: '|', isShiftRu: '/', printable: true},
    {code: 'Delete', en: 'DEL', ru: 'DEL', printable: false},
    {code: 'CapsLock', en: 'Caps Lock', ru: 'Caps Lock', nonPrintableValues: '', printable: false},
    {code: 'KeyA', en: 'a', ru: 'ф', printable: true},
    {code: 'KeyS', en: 's', ru: 'ы', printable: true},
    {code: 'KeyD', en: 'd', ru: 'в', printable: true},
    {code: 'KeyF', en: 'f', ru: 'а', printable: true},
    {code: 'KeyG', en: 'g', ru: 'п', printable: true},
    {code: 'KeyH', en: 'h', ru: 'р', printable: true},
    {code: 'KeyJ', en: 'j', ru: 'о', printable: true},
    {code: 'KeyK', en: 'k', ru: 'л', printable: true},
    {code: 'KeyL', en: 'l', ru: 'д', printable: true},
    {code: 'Semicolon', en: ';', ru: 'ж', isShiftEn: ':', printable: true},
    {code: 'Quote', en: '\'', ru: 'э', isShiftEn: '"',printable: true},
    {code: 'Enter', en: 'Enter', ru: 'Enter', nonPrintableValues: '\n', printable: false},
    {code: 'ShiftLeft', en: 'Shift', ru: 'Shift', nonPrintableValues: '', printable: false},
    {code: 'IntlBackslash', en: '\\', ru: '\\', printable: true},
    {code: 'KeyZ', en: 'z', ru: 'я', printable: true},
    {code: 'KeyX', en: 'x', ru: 'ч', printable: true},
    {code: 'KeyC', en: 'c', ru: 'с', printable: true},
    {code: 'KeyV', en: 'v', ru: 'м', printable: true},
    {code: 'KeyB', en: 'b', ru: 'и', printable: true},
    {code: 'KeyN', en: 'n', ru: 'т', printable: true},
    {code: 'KeyM', en: 'm', ru: 'ь', printable: true},
    {code: 'Comma', en: ',', ru: 'б', isShiftEn: '<',printable: true},
    {code: 'Period', en: '.', ru: 'ю', isShiftEn: '>',printable: true},
    {code: 'Slash', en: '/', ru: '.', printable: true},
    {code: 'ArrowUp', en: '▲', ru: '▲', nonPrintableValues: '▲', printable: false},
    {code: 'ShiftRight', en: 'Shift', ru: 'Shift', nonPrintableValues: '', printable: false},
    {code: 'ControlLeft', en: 'Ctrl', ru: 'Ctrl', nonPrintableValues: '', printable: false},
    {code: 'MetaLeft', en: 'Win', ru: 'Win', nonPrintableValues: '', printable: false},
    {code: 'AltLeft', en: 'Alt', ru: 'Alt', nonPrintableValues: '', printable: false},
    {code: 'Space', en: ' ', ru: ' ', printable: true},
    {code: 'AltRight', en: 'Alt', ru: 'Alt', nonPrintableValues: '', printable: false},
    {code: 'ArrowLeft', en: '◄', ru: '◄', nonPrintableValues: '◄', printable: false},
    {code: 'ArrowDown', en: '▼', ru: '▼', nonPrintableValues: '▼', printable: false},
    {code: 'ArrowRight', en: '►', ru: '►', nonPrintableValues: '►', printable: false},
    {code: 'ControlRight', en: 'Ctrl', ru: 'Ctrl', nonPrintableValues: '', printable: false}
];
