export const keyboardButtonsCode = [
    {code: 'Backquote', en: '`', ru: 'ё', isShiftEn: '~', isShiftRu: 'Ё', printable: true},
    {code: 'Digit1', en: '1', ru: '1', isShiftEn: '!', isShiftRu: '!', printable: true},
    {code: 'Digit2', en: '2', ru: '2', isShiftEn: '@', isShiftRu: '"', printable: true},
    {code: 'Digit3', en: '3', ru: '3', isShiftEn: '#', isShiftRu: '№', printable: true},
    {code: 'Digit4', en: '4', ru: '4', isShiftEn: '$', isShiftRu: ';', printable: true},
    {code: 'Digit5', en: '5', ru: '5', isShiftEn: '%', isShiftRu: '%', printable: true},
    {code: 'Digit6', en: '6', ru: '6', isShiftEn: '^', isShiftRu: ':', printable: true},
    {code: 'Digit7', en: '7', ru: '7', isShiftEn: '&', isShiftRu: '?', printable: true},
    {code: 'Digit8', en: '8', ru: '8', isShiftEn: '*', isShiftRu: '*', printable: true},
    {code: 'Digit9', en: '9', ru: '9', isShiftEn: '(', isShiftRu: '(', printable: true},
    {code: 'Digit0', en: '0', ru: '0', isShiftEn: ')', isShiftRu: ')', printable: true},
    {code: 'Minus', en: '-', ru: '-', isShiftEn: '_', isShiftRu: '_', printable: true},
    {code: 'Equal', en: '=', ru: '=', isShiftEn: '+', isShiftRu: '+', printable: true},
    {code: 'Backspace', en: 'Backspace', ru: 'Backspace', printable: false},
    {code: 'Tab', en: 'Tab', ru: 'Tab', nonPrintableValues: '     ', printable: false},
    {code: 'KeyQ', en: 'q', ru: 'й', isShiftEn: 'Q', isShiftRu: 'Й', printable: true},
    {code: 'KeyW', en: 'w', ru: 'ц', isShiftEn: 'W', isShiftRu: 'Ц', printable: true},
    {code: 'KeyE', en: 'e', ru: 'у', isShiftEn: 'Е', isShiftRu: 'У', printable: true},
    {code: 'KeyR', en: 'r', ru: 'к', isShiftEn: 'R', isShiftRu: 'К', printable: true},
    {code: 'KeyT', en: 't', ru: 'е', isShiftEn: 'T', isShiftRu: 'E', printable: true},
    {code: 'KeyY', en: 'y', ru: 'н', isShiftEn: 'Y', isShiftRu: 'H', printable: true},
    {code: 'KeyU', en: 'u', ru: 'г', isShiftEn: 'U', isShiftRu: 'Г', printable: true},
    {code: 'KeyI', en: 'i', ru: 'ш', isShiftEn: 'I', isShiftRu: 'Ш', printable: true},
    {code: 'KeyO', en: 'o', ru: 'щ', isShiftEn: 'O', isShiftRu: 'Щ', printable: true},
    {code: 'KeyP', en: 'p', ru: 'з', isShiftEn: 'Р', isShiftRu: 'З', printable: true},
    {code: 'BracketLeft', en: '[', ru: 'х', isShiftEn: '{', isShiftRu: 'Х', printable: true},
    {code: 'BracketRight', en: ']', ru: 'ъ', isShiftEn: '}', isShiftRu: 'Ъ', printable: true},
    {code: 'Backslash', en: '\\', ru: '\\', isShiftEn: '|', isShiftRu: '/', printable: true},
    {code: 'Delete', en: 'DEL', ru: 'DEL', printable: false},
    {code: 'CapsLock', en: 'Caps Lock', ru: 'Caps Lock', nonPrintableValues: '', printable: false},
    {code: 'KeyA', en: 'a', ru: 'ф', isShiftEn: 'A', isShiftRu: 'Ф' ,printable: true},
    {code: 'KeyS', en: 's', ru: 'ы', isShiftEn: 'S', isShiftRu: 'Ы', printable: true},
    {code: 'KeyD', en: 'd', ru: 'в', isShiftEn: 'D', isShiftRu: 'В', printable: true},
    {code: 'KeyF', en: 'f', ru: 'а', isShiftEn: 'F', isShiftRu: 'А', printable: true},
    {code: 'KeyG', en: 'g', ru: 'п', isShiftEn: 'G', isShiftRu: 'П', printable: true},
    {code: 'KeyH', en: 'h', ru: 'р', isShiftEn: 'H', isShiftRu: 'Р', printable: true},
    {code: 'KeyJ', en: 'j', ru: 'о', isShiftEn: 'J', isShiftRu: 'О', printable: true},
    {code: 'KeyK', en: 'k', ru: 'л', isShiftEn: 'K', isShiftRu: 'Л', printable: true},
    {code: 'KeyL', en: 'l', ru: 'д', isShiftEn: 'L', isShiftRu: 'Д', printable: true},
    {code: 'Semicolon', en: ';', ru: 'ж', isShiftEn: ':', isShiftRu: 'Ж', printable: true},
    {code: 'Quote', en: '\'', ru: 'э', isShiftEn: '"', isShiftRu: 'Э', printable: true},
    {code: 'Enter', en: 'Enter', ru: 'Enter', nonPrintableValues: '\n', printable: false},
    {code: 'ShiftLeft', en: 'Shift', ru: 'Shift', nonPrintableValues: '', printable: false},
    {code: 'IntlBackslash', en: '\\', ru: '\\', isShiftEn: '|', isShiftRu: '\\', printable: true},
    {code: 'KeyZ', en: 'z', ru: 'я', isShiftEn: 'Z', isShiftRu: 'Я', printable: true},
    {code: 'KeyX', en: 'x', ru: 'ч', isShiftEn: 'X', isShiftRu: 'Ч', printable: true},
    {code: 'KeyC', en: 'c', ru: 'с', isShiftEn: 'C', isShiftRu: 'С', printable: true},
    {code: 'KeyV', en: 'v', ru: 'м', isShiftEn: 'V', isShiftRu: 'М', printable: true},
    {code: 'KeyB', en: 'b', ru: 'и', isShiftEn: 'B', isShiftRu: 'И', printable: true},
    {code: 'KeyN', en: 'n', ru: 'т', isShiftEn: 'N', isShiftRu: 'Т', printable: true},
    {code: 'KeyM', en: 'm', ru: 'ь', isShiftEn: 'M', isShiftRu: 'Ь', printable: true},
    {code: 'Comma', en: ',', ru: 'б', isShiftRu: 'Б', isShiftEn: '<',printable: true},
    {code: 'Period', en: '.', ru: 'ю', isShiftRu: 'Ю', isShiftEn: '>',printable: true},
    {code: 'Slash', en: '/', ru: '.', isShiftEn: '?', isShiftRu: '?', printable: true},
    {code: 'ArrowUp', en: '▲', ru: '▲', nonPrintableValues: '▲', printable: false},
    {code: 'ShiftRight', en: 'Shift', ru: 'Shift', nonPrintableValues: '', printable: false},
    {code: 'ControlLeft', en: 'Ctrl', ru: 'Ctrl', nonPrintableValues: '', printable: false},
    {code: 'MetaLeft', en: 'Win', ru: 'Win', nonPrintableValues: '', printable: false},
    {code: 'AltLeft', en: 'Alt', ru: 'Alt', nonPrintableValues: '', printable: false},
    {code: 'Space', en: ' ', ru: ' ', isShiftEn: ' ', isShiftRu: ' ', printable: true},
    {code: 'AltRight', en: 'Alt', ru: 'Alt', nonPrintableValues: '', printable: false},
    {code: 'ArrowLeft', en: '◄', ru: '◄', nonPrintableValues: '◄', printable: false},
    {code: 'ArrowDown', en: '▼', ru: '▼', nonPrintableValues: '▼', printable: false},
    {code: 'ArrowRight', en: '►', ru: '►', nonPrintableValues: '►', printable: false},
    {code: 'ControlRight', en: 'Ctrl', ru: 'Ctrl', nonPrintableValues: '', printable: false}
];
